import { CDinfo } from "@/lib/cd_consts";
import { create } from "zustand";

export interface UseCdInfo {
  cdInfo: CDinfo;
  set: (cdInfo: CDinfo) => void;
}

export const useCdInfo = create<UseCdInfo>((set) => ({
  cdInfo: {
    name: "RR",
    time: {
      typeOfTime: 0,
      pers_time_utc: {
        year: 1978,
        month: 5,
        day: 17,
        hours: 0,
        minutes: 45,
      },
      pers_time_local: {
        year: 0,
        month: 0,
        day: 0,
        hours: 0,
        minutes: 0,
        offset: 0,
        place: "",
        longitude: 0,
        latitude: 0,
      },
      pers_time_sec: -682470851.47,
      des_time: {
        year: 1978,
        month: 2,
        day: 17,
        hours: 6,
        minutes: 46,
        seconds: 7,
      },
      des_time_sec: -690181984.513614,
    },
    hd: {
      personality: {
        generalInfo: {
          authority: "Self projected",
          type: "Projector",
          definition: "Single Definition",
        },
        gates: [
          { defined: false, number: 0, pers: false, des: false },
          { defined: true, number: 1, pers: true, des: false },
          { defined: false, number: 2, pers: false, des: false },
          { defined: true, number: 3, pers: true, des: false },
          { defined: true, number: 4, pers: true, des: false },
          { defined: false, number: 5, pers: false, des: false },
          { defined: false, number: 6, pers: false, des: false },
          { defined: true, number: 7, pers: true, des: false },
          { defined: true, number: 8, pers: true, des: false },
          { defined: false, number: 9, pers: false, des: false },
          { defined: false, number: 10, pers: false, des: false },
          { defined: false, number: 11, pers: false, des: false },
          { defined: true, number: 12, pers: true, des: false },
          { defined: false, number: 13, pers: false, des: false },
          { defined: true, number: 14, pers: true, des: false },
          { defined: false, number: 15, pers: false, des: false },
          { defined: false, number: 16, pers: false, des: false },
          { defined: true, number: 17, pers: true, des: false },
          { defined: true, number: 18, pers: true, des: false },
          { defined: false, number: 19, pers: false, des: false },
          { defined: false, number: 20, pers: false, des: false },
          { defined: false, number: 21, pers: false, des: false },
          { defined: false, number: 22, pers: false, des: false },
          { defined: false, number: 23, pers: false, des: false },
          { defined: false, number: 24, pers: false, des: false },
          { defined: false, number: 25, pers: false, des: false },
          { defined: true, number: 26, pers: true, des: false },
          { defined: false, number: 27, pers: false, des: false },
          { defined: false, number: 28, pers: false, des: false },
          { defined: false, number: 29, pers: false, des: false },
          { defined: false, number: 30, pers: false, des: false },
          { defined: false, number: 31, pers: false, des: false },
          { defined: false, number: 32, pers: false, des: false },
          { defined: false, number: 33, pers: false, des: false },
          { defined: false, number: 34, pers: false, des: false },
          { defined: false, number: 35, pers: false, des: false },
          { defined: false, number: 36, pers: false, des: false },
          { defined: false, number: 37, pers: false, des: false },
          { defined: false, number: 38, pers: false, des: false },
          { defined: false, number: 39, pers: false, des: false },
          { defined: false, number: 40, pers: false, des: false },
          { defined: false, number: 41, pers: false, des: false },
          { defined: false, number: 42, pers: false, des: false },
          { defined: false, number: 43, pers: false, des: false },
          { defined: false, number: 44, pers: false, des: false },
          { defined: false, number: 45, pers: false, des: false },
          { defined: false, number: 46, pers: false, des: false },
          { defined: true, number: 47, pers: true, des: false },
          { defined: true, number: 48, pers: true, des: false },
          { defined: false, number: 49, pers: false, des: false },
          { defined: false, number: 50, pers: false, des: false },
          { defined: false, number: 51, pers: false, des: false },
          { defined: true, number: 52, pers: true, des: false },
          { defined: false, number: 53, pers: false, des: false },
          { defined: false, number: 54, pers: false, des: false },
          { defined: false, number: 55, pers: false, des: false },
          { defined: false, number: 56, pers: false, des: false },
          { defined: false, number: 57, pers: false, des: false },
          { defined: false, number: 58, pers: false, des: false },
          { defined: false, number: 59, pers: false, des: false },
          { defined: false, number: 60, pers: false, des: false },
          { defined: false, number: 61, pers: false, des: false },
          { defined: false, number: 62, pers: false, des: false },
          { defined: false, number: 63, pers: false, des: false },
          { defined: false, number: 64, pers: false, des: false },
        ],
        channels: [
          {
            defined: false,
            number: 0,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 1,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 2,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 3,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 4,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 5,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 6,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 7,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 8,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 9,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 10,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 11,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 12,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 13,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 14,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: true,
            number: 15,
            firstGate: { defined: true, number: 1, pers: true, des: false },
            secondGate: { defined: true, number: 8, pers: true, des: false },
          },
          {
            defined: false,
            number: 16,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 17,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 18,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 19,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 20,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 21,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 22,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 23,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 24,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 25,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 26,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 27,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 28,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 29,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 30,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 31,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 32,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 33,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 34,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 35,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 36,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
        ],
        centers: {
          Head: false,
          Ajna: false,
          Throat: true,
          G: true,
          Sacral: false,
          Root: false,
          Ego: false,
          Spleen: false,
          Emo: false,
        },
        planets_data: [
          {
            hex: 0,
            line: 0,
            color: 0,
            tone: 0,
            base: 0,
            longitude: 0,
            power: 0,
            direction: "",
            name: "",
            number: 0,
            zodiac: {
              name: "",
              degrees: 0,
              minutes: 0,
              seconds: 0,
              text: "",
            },
          },
          {
            hex: 3,
            line: 5.843702771216613,
            color: 5.0622166272996765,
            tone: 0.37329976379805885,
            base: 1.866498818990294,
            number_of_passed_degrees: 5.4784713480155744,
            longitude: 0.5559479532125483,
            power: 4,
            direction: "D",
            name: "mercury",
            number: 1,
          },
          {
            hex: 12,
            line: 2.3486575054991286,
            color: 2.091945032994772,
            tone: 0.5516701979686331,
            base: 2.7583509898431653,
            number_of_passed_degrees: 2.201866411405433,
            longitude: 1.4805081130284117,
            power: 4,
            direction: "D",
            name: "venus",
            number: 2,
          },
          {
            hex: 14,
            line: 2.200337071611466,
            color: 1.2020224296687956,
            tone: 1.212134578012774,
            base: 1.0606728900638696,
            number_of_passed_degrees: 2.0628160046357493,
            longitude: 4.128800027070431,
            power: 7,
            direction: "D",
            name: "earth",
            number: 3,
          },
          {
            hex: 7,
            line: 2.901302835564608,
            color: 5.407817013387648,
            tone: 2.44690208032589,
            base: 2.234510401629449,
            number_of_passed_degrees: 2.71997140834182,
            longitude: 2.373123684918116,
            power: 4,
            direction: "D",
            name: "mars",
            number: 4,
          },
          {
            hex: 52,
            line: 2.7601703587544155,
            color: 4.561022152526493,
            tone: 3.3661329151589596,
            base: 1.8306645757947988,
            number_of_passed_degrees: 2.5876597113322646,
            longitude: 1.6835910171936308,
            power: 5,
            direction: "D",
            name: "jupiter",
            number: 5,
          },
          {
            hex: 4,
            line: 5.875241549116406,
            color: 5.251449294698432,
            tone: 1.5086957681905915,
            base: 2.543478840952957,
            number_of_passed_degrees: 5.50803895229663,
            longitude: 2.5199594137528,
            power: 0,
            direction: "D",
            name: "saturn",
            number: 6,
          },
          {
            hex: 1,
            line: 0.9848301890993449,
            color: 5.90898113459607,
            tone: 5.453886807576418,
            base: 2.2694340378820903,
            number_of_passed_degrees: 0.9232783022806359,
            longitude: 3.9125618013643613,
            power: 5,
            direction: "R",
            name: "uranus",
            number: 7,
          },
          {
            hex: 26,
            line: 0.8643676300439741,
            color: 5.186205780263845,
            tone: 1.1172346815830678,
            base: 0.586173407915339,
            number_of_passed_degrees: 0.8103446531662257,
            longitude: 4.499639359899109,
            power: 6,
            direction: "R",
            name: "neptune",
            number: 8,
          },
          {
            hex: 48,
            line: 5.411180674054594,
            color: 2.4670840443275663,
            tone: 2.802504265965399,
            base: 4.012521329826995,
            number_of_passed_degrees: 5.072981881926182,
            longitude: 3.3959391692628844,
            power: 0,
            direction: "R",
            name: "pluto",
            number: 9,
          },
          {
            hex: 8,
            line: 2.200337071611496,
            color: 1.2020224296689777,
            tone: 1.2121345780138653,
            base: 1.0606728900693265,
            number_of_passed_degrees: 2.0628160046357777,
            longitude: 0.9872073734806385,
            power: 3,
            direction: "D",
            name: "sun",
            number: 10,
          },
          {
            hex: 47,
            line: 5.21248932439427,
            color: 1.274935946365622,
            tone: 1.6496156781937314,
            base: 3.2480783909686575,
            number_of_passed_degrees: 4.886708741619628,
            longitude: 2.999989007957782,
            power: 2,
            direction: "D",
            name: "moon",
            number: 11,
          },
          {
            hex: 18,
            line: 1.212266015332989,
            color: 1.2735960919979334,
            tone: 1.6415765519876002,
            base: 3.2078827599380015,
            number_of_passed_degrees: 1.136499389374677,
            longitude: 3.229059818396067,
            power: 7,
            direction: "R",
            name: "north_node",
            number: 12,
          },
          {
            hex: 17,
            line: 1.2122660153329974,
            color: 1.2735960919979845,
            tone: 1.6415765519879073,
            base: 3.2078827599395363,
            number_of_passed_degrees: 1.136499389374685,
            longitude: 0.08746716480627358,
            power: 7,
            direction: "R",
            name: "south_node",
            number: 13,
          },
        ],
      },
      design: {
        generalInfo: {
          authority: "No inner authority",
          type: "Projector",
          definition: "Single Definition",
        },
        gates: [
          { defined: false, number: 0, pers: false, des: false },
          { defined: true, number: 1, pers: true, des: true },
          { defined: false, number: 2, pers: false, des: false },
          { defined: false, number: 3, pers: false, des: false },
          { defined: false, number: 4, pers: false, des: false },
          { defined: false, number: 5, pers: false, des: false },
          { defined: false, number: 6, pers: false, des: false },
          { defined: false, number: 7, pers: false, des: false },
          { defined: false, number: 8, pers: false, des: false },
          { defined: false, number: 9, pers: false, des: false },
          { defined: false, number: 10, pers: false, des: false },
          { defined: false, number: 11, pers: false, des: false },
          { defined: true, number: 12, pers: true, des: true },
          { defined: false, number: 13, pers: false, des: false },
          { defined: false, number: 14, pers: false, des: false },
          { defined: false, number: 15, pers: false, des: false },
          { defined: false, number: 16, pers: false, des: false },
          { defined: true, number: 17, pers: true, des: true },
          { defined: true, number: 18, pers: true, des: true },
          { defined: false, number: 19, pers: false, des: false },
          { defined: false, number: 20, pers: false, des: false },
          { defined: false, number: 21, pers: false, des: false },
          { defined: false, number: 22, pers: false, des: false },
          { defined: false, number: 23, pers: false, des: false },
          { defined: false, number: 24, pers: false, des: false },
          { defined: false, number: 25, pers: false, des: false },
          { defined: true, number: 26, pers: true, des: true },
          { defined: false, number: 27, pers: false, des: false },
          { defined: false, number: 28, pers: false, des: false },
          { defined: true, number: 29, pers: false, des: true },
          { defined: true, number: 30, pers: false, des: true },
          { defined: false, number: 31, pers: false, des: false },
          { defined: false, number: 32, pers: false, des: false },
          { defined: false, number: 33, pers: false, des: false },
          { defined: false, number: 34, pers: false, des: false },
          { defined: false, number: 35, pers: false, des: false },
          { defined: false, number: 36, pers: false, des: false },
          { defined: false, number: 37, pers: false, des: false },
          { defined: false, number: 38, pers: false, des: false },
          { defined: false, number: 39, pers: false, des: false },
          { defined: false, number: 40, pers: false, des: false },
          { defined: false, number: 41, pers: false, des: false },
          { defined: false, number: 42, pers: false, des: false },
          { defined: false, number: 43, pers: false, des: false },
          { defined: false, number: 44, pers: false, des: false },
          { defined: false, number: 45, pers: false, des: false },
          { defined: false, number: 46, pers: false, des: false },
          { defined: false, number: 47, pers: false, des: false },
          { defined: false, number: 48, pers: false, des: false },
          { defined: true, number: 49, pers: false, des: true },
          { defined: false, number: 50, pers: false, des: false },
          { defined: false, number: 51, pers: false, des: false },
          { defined: false, number: 52, pers: false, des: false },
          { defined: false, number: 53, pers: false, des: false },
          { defined: false, number: 54, pers: false, des: false },
          { defined: true, number: 55, pers: false, des: true },
          { defined: false, number: 56, pers: false, des: false },
          { defined: true, number: 57, pers: false, des: true },
          { defined: false, number: 58, pers: false, des: false },
          { defined: false, number: 59, pers: false, des: false },
          { defined: false, number: 60, pers: false, des: false },
          { defined: false, number: 61, pers: false, des: false },
          { defined: true, number: 62, pers: false, des: true },
          { defined: false, number: 63, pers: false, des: false },
          { defined: false, number: 64, pers: false, des: false },
        ],
        channels: [
          {
            defined: false,
            number: 0,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 1,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 2,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 3,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: true,
            number: 4,
            firstGate: { defined: true, number: 17, pers: true, des: true },
            secondGate: { defined: true, number: 62, pers: false, des: true },
          },
          {
            defined: false,
            number: 5,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 6,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 7,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 8,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 9,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 10,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 11,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 12,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 13,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 14,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 15,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 16,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 17,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 18,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 19,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 20,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 21,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 22,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 23,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 24,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 25,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 26,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 27,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 28,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 29,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 30,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 31,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 32,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 33,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 34,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 35,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
          {
            defined: false,
            number: 36,
            firstGate: { defined: false, number: 0, pers: false, des: false },
            secondGate: {
              defined: false,
              number: 0,
              pers: false,
              des: false,
            },
          },
        ],
        centers: {
          Head: false,
          Ajna: true,
          Throat: true,
          G: false,
          Sacral: false,
          Root: false,
          Ego: false,
          Spleen: false,
          Emo: false,
        },
        planets_data: [
          {
            hex: 0,
            line: 0,
            color: 0,
            tone: 0,
            base: 0,
            longitude: 0,
            power: 0,
            direction: "",
            name: "",
            number: 0,
            zodiac: {
              name: "",
              degrees: 0,
              minutes: 0,
              seconds: 0,
              text: "",
            },
          },
          {
            hex: 49,
            line: 2.103581361991807,
            color: 0.6214881719508412,
            tone: 3.728929031705047,
            base: 3.6446451585252357,
            number_of_passed_degrees: 1.972107526867319,
            longitude: 5.599838421844115,
            power: 4,
            direction: "D",
            name: "mercury",
            number: 1,
          },
          {
            hex: 55,
            line: 5.02794122037673,
            color: 0.16764732226038176,
            tone: 1.0058839335622907,
            base: 0.029419667811452884,
            number_of_passed_degrees: 4.713694894103185,
            longitude: 5.8440376889828265,
            power: 5,
            direction: "D",
            name: "venus",
            number: 2,
          },
          {
            hex: 29,
            line: 4.333678911800507,
            color: 2.002073470803043,
            tone: 0.012440824818258988,
            base: 0.062204124091294936,
            number_of_passed_degrees: 4.0628239798129755,
            longitude: 2.5929104245085224,
            power: 7,
            direction: "D",
            name: "earth",
            number: 3,
          },
          {
            hex: 62,
            line: 3.127968541531239,
            color: 0.7678112491874345,
            tone: 4.6068674951246065,
            base: 3.034337475623032,
            number_of_passed_degrees: 2.9324705076855366,
            longitude: 1.9841334121604624,
            power: 1,
            direction: "R",
            name: "mars",
            number: 4,
          },
          {
            hex: 12,
            line: 4.0162360157232495,
            color: 0.09741609433949634,
            tone: 0.584496566036978,
            base: 2.9224828301848897,
            number_of_passed_degrees: 3.7652212647405463,
            longitude: 1.5077938025961424,
            power: 0,
            direction: "R",
            name: "jupiter",
            number: 5,
          },
          {
            hex: 29,
            line: 3.0325300148123158,
            color: 0.19518008887389443,
            tone: 1.1710805332433665,
            base: 0.8554026662168323,
            number_of_passed_degrees: 2.842996888886546,
            longitude: 2.571620425466832,
            power: 0,
            direction: "R",
            name: "saturn",
            number: 6,
          },
          {
            hex: 1,
            line: 3.6899435900476116,
            color: 4.13966154028567,
            tone: 0.8379692417140177,
            base: 4.189846208570088,
            number_of_passed_degrees: 3.459322115669636,
            longitude: 3.956824115882832,
            power: 5,
            direction: "D",
            name: "uranus",
            number: 7,
          },
          {
            hex: 26,
            line: 1.441701238201434,
            color: 2.6502074292086037,
            tone: 3.901244575251621,
            base: 4.506222876258106,
            number_of_passed_degrees: 1.3515949108138443,
            longitude: 4.509085958972327,
            power: 6,
            direction: "D",
            name: "neptune",
            number: 8,
          },
          {
            hex: 57,
            line: 1.73788787800695,
            color: 4.427327268041699,
            tone: 2.5639636082501966,
            base: 2.819818041250982,
            number_of_passed_degrees: 1.6292698856315155,
            longitude: 3.434009826861797,
            power: 0,
            direction: "R",
            name: "pluto",
            number: 9,
          },
          {
            hex: 30,
            line: 4.333678911800537,
            color: 2.002073470803225,
            tone: 0.012440824819350382,
            base: 0.062204124096751905,
            number_of_passed_degrees: 4.062823979813004,
            longitude: 5.7345030780983155,
            power: 0,
            direction: "D",
            name: "sun",
            number: 10,
          },
          {
            hex: 12,
            line: 1.7859543956298543,
            color: 4.715726373779125,
            tone: 4.294358242674752,
            base: 1.4717912133737616,
            number_of_passed_degrees: 1.6743322459029883,
            longitude: 1.4713009049236332,
            power: 3,
            direction: "D",
            name: "moon",
            number: 11,
          },
          {
            hex: 18,
            line: 3.020000970394752,
            color: 0.12000582236851187,
            tone: 0.7200349342110712,
            base: 3.6001746710553557,
            number_of_passed_degrees: 2.83125090974508,
            longitude: 3.2586388124297097,
            power: 7,
            direction: "R",
            name: "north_node",
            number: 12,
          },
          {
            hex: 17,
            line: 3.0200009703947415,
            color: 0.12000582236844934,
            tone: 0.7200349342106961,
            base: 3.60017467105348,
            number_of_passed_degrees: 2.83125090974507,
            longitude: 0.11704615883991655,
            power: 7,
            direction: "R",
            name: "south_node",
            number: 13,
          },
        ],
      },
      generalInfo: {
        authority: "Self projected",
        type: "Projector",
        definition: "Single Definition",
      },
      specialInfo: {
        theme: "Theme: Thirst",
        nutr_type: "Type: Hot",
        cognition: "Cogn.: Smell",
        motivation: "Hope",
        mind: "Theist",
        profile: "3/5",
        variable: "PLL DLL",
        cross: { first: 8, second: 14, third: 30, fourth: 29 },
      },
      gates: [
        { defined: false, number: 0, pers: false, des: false },
        { defined: true, number: 1, pers: true, des: true },
        { defined: false, number: 2, pers: false, des: false },
        { defined: true, number: 3, pers: true, des: false },
        { defined: true, number: 4, pers: true, des: false },
        { defined: false, number: 5, pers: false, des: false },
        { defined: false, number: 6, pers: false, des: false },
        { defined: true, number: 7, pers: true, des: false },
        { defined: true, number: 8, pers: true, des: false },
        { defined: false, number: 9, pers: false, des: false },
        { defined: false, number: 10, pers: false, des: false },
        { defined: false, number: 11, pers: false, des: false },
        { defined: true, number: 12, pers: true, des: true },
        { defined: false, number: 13, pers: false, des: false },
        { defined: true, number: 14, pers: true, des: false },
        { defined: false, number: 15, pers: false, des: false },
        { defined: false, number: 16, pers: false, des: false },
        { defined: true, number: 17, pers: true, des: true },
        { defined: true, number: 18, pers: true, des: true },
        { defined: false, number: 19, pers: false, des: false },
        { defined: false, number: 20, pers: false, des: false },
        { defined: false, number: 21, pers: false, des: false },
        { defined: false, number: 22, pers: false, des: false },
        { defined: false, number: 23, pers: false, des: false },
        { defined: false, number: 24, pers: false, des: false },
        { defined: false, number: 25, pers: false, des: false },
        { defined: true, number: 26, pers: true, des: true },
        { defined: false, number: 27, pers: false, des: false },
        { defined: false, number: 28, pers: false, des: false },
        { defined: true, number: 29, pers: false, des: true },
        { defined: true, number: 30, pers: false, des: true },
        { defined: false, number: 31, pers: false, des: false },
        { defined: false, number: 32, pers: false, des: false },
        { defined: false, number: 33, pers: false, des: false },
        { defined: false, number: 34, pers: false, des: false },
        { defined: false, number: 35, pers: false, des: false },
        { defined: false, number: 36, pers: false, des: false },
        { defined: false, number: 37, pers: false, des: false },
        { defined: false, number: 38, pers: false, des: false },
        { defined: false, number: 39, pers: false, des: false },
        { defined: false, number: 40, pers: false, des: false },
        { defined: false, number: 41, pers: false, des: false },
        { defined: false, number: 42, pers: false, des: false },
        { defined: false, number: 43, pers: false, des: false },
        { defined: false, number: 44, pers: false, des: false },
        { defined: false, number: 45, pers: false, des: false },
        { defined: false, number: 46, pers: false, des: false },
        { defined: true, number: 47, pers: true, des: false },
        { defined: true, number: 48, pers: true, des: false },
        { defined: true, number: 49, pers: false, des: true },
        { defined: false, number: 50, pers: false, des: false },
        { defined: false, number: 51, pers: false, des: false },
        { defined: true, number: 52, pers: true, des: false },
        { defined: false, number: 53, pers: false, des: false },
        { defined: false, number: 54, pers: false, des: false },
        { defined: true, number: 55, pers: false, des: true },
        { defined: false, number: 56, pers: false, des: false },
        { defined: true, number: 57, pers: false, des: true },
        { defined: false, number: 58, pers: false, des: false },
        { defined: false, number: 59, pers: false, des: false },
        { defined: false, number: 60, pers: false, des: false },
        { defined: false, number: 61, pers: false, des: false },
        { defined: true, number: 62, pers: false, des: true },
        { defined: false, number: 63, pers: false, des: false },
        { defined: false, number: 64, pers: false, des: false },
      ],
      channels: [
        {
          defined: false,
          number: 0,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 1,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 2,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 3,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: true,
          number: 4,
          firstGate: { defined: true, number: 17, pers: true, des: true },
          secondGate: { defined: true, number: 62, pers: false, des: true },
        },
        {
          defined: false,
          number: 5,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 6,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 7,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 8,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 9,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 10,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 11,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 12,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 13,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 14,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: true,
          number: 15,
          firstGate: { defined: true, number: 1, pers: true, des: true },
          secondGate: { defined: true, number: 8, pers: true, des: false },
        },
        {
          defined: false,
          number: 16,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 17,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 18,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 19,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 20,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 21,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 22,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 23,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 24,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 25,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 26,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 27,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 28,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 29,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 30,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 31,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 32,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 33,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 34,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 35,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
        {
          defined: false,
          number: 36,
          firstGate: { defined: false, number: 0, pers: false, des: false },
          secondGate: { defined: false, number: 0, pers: false, des: false },
        },
      ],
      centers: {
        Head: false,
        Ajna: true,
        Throat: true,
        G: true,
        Sacral: false,
        Root: false,
        Ego: false,
        Spleen: false,
        Emo: false,
      },
    },
    fdInfo: {},
    numerologyInfo: {},
    astroInfo: {
    },
  },

  set: (data: CDinfo) => set(() => ({ cdInfo: data })),
}));
